/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        // --- Existing tokens: untouched, still power Landing/About ---
        paper: '#F7F5F0',
        ink: '#12141A',
        'ink-soft': '#3A3D45',
        'ink-muted': '#5E6068',
        'ink-faint': '#8A8D93',
        teal: '#2C7A6B',
        hairline: '#DFDAD0',
        destructive: '#C1502E',
        success: '#2F6B5A',
        muted: '#EDE9DF',
        'muted-foreground': '#5E6068',
        background: '#F7F5F0',
        foreground: '#12141A',
        primary: '#12141A',
        border: '#DFDAD0',
        input: '#DFDAD0',
        accent: '#2C7A6B',
        ring: '#2C7A6B',

        // --- New tokens: app-zone rebrand only (Home, Predict, History, Trends, Explore, auth) ---
        'app-bg': '#FFFFFF',
        'app-surface': '#F8F9FB',
        'app-ink': '#0F172A',
        'app-ink-soft': '#334155',
        'app-ink-muted': '#64748B',
        'app-ink-faint': '#94A3B8',
        'app-accent': '#5B4FE9',
        'app-accent-soft': '#EEECFD',
        'app-accent-hover': '#4C41D1',
        'app-hairline': '#E5E7EB',
        'app-destructive': '#EF4444',
        'app-success': '#16A34A',
        // Semantic prediction-result colors — reserved, R/S/I only
        resistant: '#FF3B30',
        susceptible: '#30D158',
        intermediate: '#FF9F0A',

        // --- Apple-calibrated tokens: Predict & History redesign only ---
        canvas: '#FFFFFF',
        'canvas-alt': '#F5F5F7',
        'canvas-hairline': '#D2D2D7',
        panel: '#1D1D1F',
        'panel-raised': '#2C2C2E',
        'panel-border': '#3A3A3C',
        'onpanel-ink': '#F5F5F7',
        'onpanel-muted': '#98989D',
        'onpanel-faint': '#6E6E73',
        'page-ink': '#1D1D1F',
        'page-muted': '#6E6E73',
        'page-faint': '#86868B',
        'accent-blue': '#0071E3',
        'accent-blue-hover': '#0077ED',
        'accent-blue-active': '#0066CC',

        'accent-indigo': '#5E5CE6',
        'accent-indigo-soft': '#EEEDFC',
        'accent-teal': '#30B0C7',
        'accent-teal-soft': '#E5F6F9',
      },
      fontFamily: {
        sans: ['Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        serif: ['Fraunces', 'ui-serif', 'Georgia', 'serif'],
        mono: ['"JetBrains Mono"', 'ui-monospace', 'SFMono-Regular', 'monospace'],
        display: ['"Space Grotesk"', 'Inter', 'ui-sans-serif', 'sans-serif'],
      },
      fontSize: {
        hero: ['56px', { lineHeight: '1.05', letterSpacing: '-0.02em', fontWeight: '600' }],
        h1: ['40px', { lineHeight: '1.1', letterSpacing: '-0.015em', fontWeight: '600' }],
        h2: ['28px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '600' }],
        h3: ['20px', { lineHeight: '1.3', letterSpacing: '-0.005em', fontWeight: '600' }],
        h4: ['16px', { lineHeight: '1.4', letterSpacing: '0em', fontWeight: '600' }],
        subtitle: ['16px', { lineHeight: '1.5', letterSpacing: '0em', fontWeight: '500' }],
        'body-lg': ['16px', { lineHeight: '1.6', letterSpacing: '0em', fontWeight: '400' }],
        body: ['14px', { lineHeight: '1.6', letterSpacing: '0em', fontWeight: '400' }],
        small: ['13px', { lineHeight: '1.5', letterSpacing: '0em', fontWeight: '400' }],
        caption: ['12px', { lineHeight: '1.4', letterSpacing: '0.01em', fontWeight: '400' }],
        label: ['12px', { lineHeight: '1.2', letterSpacing: '0.02em', fontWeight: '600' }],
        'mono-label': ['11px', { lineHeight: '1.2', letterSpacing: '0.08em', fontWeight: '500' }],
      },
      boxShadow: {
        'panel-sm': '0 1px 2px rgba(0,0,0,0.24), 0 1px 1px rgba(0,0,0,0.12)',
        'panel-md': '0 2px 8px rgba(0,0,0,0.28), 0 1px 2px rgba(0,0,0,0.16)',
        'panel-lg': '0 8px 24px rgba(0,0,0,0.32), 0 2px 6px rgba(0,0,0,0.18)',
        'card-flat': '0 1px 2px rgba(0,0,0,0.04)',
        'focus-ring': '0 0 0 4px rgba(0,113,227,0.25)',
      },
    },
  },
  plugins: [],
}